### ISSUE TITLE
<name> tags of any use?

### ISSUE THREAD

**Issue by AngledLuffa** [EmilStenstrom/suc_to_iob#3]
One thing I noticed is that in sentences such as

```
Perstorp        B-LOC/ORG
tidigt  O
ute     O
i       O
Moselle O
```

`Moselle` is definitely a LOC in this context, and in the scrambled version of the dataset it has the following kind of tag in such situations:

```
<name type="place">
<w blingbring="|" complemgram="|" compwf="|" dephead="06" deprel="PA" lemma="|Moselle|" lex="|" msd="PM.NOM" pos="PM" prefix="|" ref="07" sense="|" suffix="|" swefn="|">Moselle</w>
</name>
```

Are these annotations also present in the unscrambled dataset?  The description on the official site suggests it is:

```
The following annotation is taken from the official version:

Part of speech (pos attributes of word elements)
Morphology (msd attributes)
Lemma (lemma attributes)
Named entity (SUC 3.0 only; <name> tags, not the <ne> tags)
All other annotation, like the linking against Saldo, the dependency parses, and alternative named entity annotation (<ne> tags), was created automatically by Sparv.
```

Based on this, how do you feel about an option which extracts `<name>` instead of, or in addition to, the `<ne>` tags?

**Comment by EmilStenstrom** [comment]
@AngledLuffa Hi again. I've now made A LOT of improvements to this script. The algorithm is described in the README on the repo front page. But to address your specific concerns above:

* The name tag is used instead of ne tag when possible
* But also the ne tag when no name exists
* All ambiguous tags with "/" in them have been simplified to just one tag.
* Fixed locations mapped to institutions 
* ... and a couple of other fixes

I've manually went through the resulting file to check for inconsistencies, and things look better now!

I'd love to see this be part of a NER module for Swedish in **stanza**, so if there's anything I can do to help, let me know!

**Comment by AngledLuffa** [comment]
I can give it a try!  As I mentioned in the issue on stanza, we do already have a model based on the previous version of the script.  However, the new version has at least one issue I think - the output statements are commented out!

I had made a change to our own version where it had a flag to output results to a file.  It was quite useful, especially for our purposes.  I'll make a PR to include that functionality here.

**Comment by EmilStenstrom** [comment]
So, you're saying I should test my code before pushing it! ;) I have fixed that bug a moment ago... thanks for pointing it out.

**Comment by AngledLuffa** [comment]
Ha!  Testing is overrated.  I just opened a PR which also included writing to a user requested file... this represents the easiest way for us to use it, since then we wrap the whole thing in another script which splits the output into train/dev/test splits.
